### ISSUE TITLE
Build a visual vocabulary

### ISSUE THREAD

**Issue by willard-yuan** [tsattler/geometric_burstiness#1]
@tsattler Hi tsattler. When running `compute_word_assignments`, the input requires a visual vocabulary. So to compute word assignments, I need to write all the 128-D rootsift descriptors extracted from images to a text file (i.e. vocabulary). Did I understand it right?

**Comment by tsattler** [comment]
@willard-yuan You will need to train a visual vocabulary from the descriptors extracted from the images that you then pass on to compute_word_assignments. Training of the vocabulary is done by running (approximate) k-means (where k is the desired number of cluster centers) on all descriptors extracted from the images or a subset of them.

**Comment by willard-yuan** [comment]
Thanks
