### ISSUE TITLE
Visual Vocabulary

### ISSUE THREAD

**Issue by francescoli** [tsattler/geometric_burstiness#11]
@tsattler Is there any visual vocabulary ready to use available, or I must train it myself?

**Comment by tsattler** [comment]
@francescoli Unfortunately, there is no visual vocabulary that is ready to use. You will need to train a vocabulary yourself. You could for example use Facebook's FAISS library for this.

**Comment by francescoli** [comment]
@tsattler got it, you mean this project https://github.com/facebookresearch/faiss ?

**Comment by tsattler** [comment]
@francescoli yes, that is the one i meant.

**Comment by francescoli** [comment]
Thank you

**Comment by francescoli** [comment]
@tsattler I'm still confused about how to train the vocabulary. The demos in faiss don't generate the vocabulary file that you described. Could you please give me more hints?

**Comment by tsattler** [comment]
@francescoli You will need to write out the descriptors that you want to use for computing the vocabulary into a file. You can then load that data, pass it to the FAISS library, and cluster it. You can find example code for clustering (in Python) here: https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization#clustering . The result of running that code will be a matrix containing the cluster centers (if I am not mistaken, each row corresponds to a cluster center), which you can save into a text file.

For training a visual vocabulary of X words, I recommend using around 10 * X many descriptors.

**Comment by francescoli** [comment]
Grateful, I will have a try
