### ISSUE TITLE
Query Time

### ISSUE THREAD

**Issue by francescoli** [tsattler/geometric_burstiness#12]
Hi, @tsattler , I met the same problem as #2 metioned. The images of the database are captured uniformly on the trajectory of the camera inside the room. So the adjacent ones look the same. Does it matter? I trained the vocabulary with the dataset ANN_SIFT1M(http://corpus-texmex.irisa.fr/), and both database images and query images are extracted with hesaff. Anything Wrong?

Here is the log
```
 Loading the inverted index 
 Index loaded 
 Weights loaded 
 Found 2 query files 
 Found 836 db images in image_db.txt

 Query 0 : ./q/000230.jpg.bin

  Prepared 1287 query descriptors 
  Computing the self-similarity for the query image from 1287 query descriptors 
  Self-similarity: 26333.7
  Normalization weight 0.00616232
  Query found 836 potentially relevant database images
  Score of most relevant image 0.0912435 (image 726) with 4322 matches
  Starting spatial verification
```

**Comment by tsattler** [comment]
@francescoli In my experience, different SIFT implementations are not necessarily compatible (the order in which histogram bins are concatenated into a single descriptor is not uniquely defined). Are you using RootSIFT descriptors or normal SIFT descriptors for retrieval (I'd assume that the SIFT1M descriptors are not RootSIFT descriptors, which will most likely lead to problems when training a vocabulary on standard descriptors and then using it for RootSIFT descriptors).

Have you tried learning the vocabulary from the features found in the database images? In my experience, this should give the best performance.

**Comment by francescoli** [comment]
Yes， SIFT1M uses normal SIFT, I also tried that convert SIFT1M descriptors to RootSIFT with my own implementation. But all the descriptor values are smaller than 1.0, while in consider of the code
https://github.com/tsattler/geometric_burstiness/blob/8a02fa7e223f8ffba228c1a11d93e1f0d6a41c19/src/compute_word_assignments.cc#L110,
I guessed normal SIFT would be the proper one. After checking the code of hesaff, I find the difference against mine after computing square root. That could be the point.
https://github.com/perdoch/hesaff/blob/0d939a424372ed7dd23ecc0b3590f37122695cbc/siftdesc.cpp#L110
Emm, I will test the performance between the vocabulary form SIFT1M and the one with images in my room.
Thanks for your suggestions.

**Comment by tsattler** [comment]
@francescoli Originally, SIFT is normalized to unit length, i.e., each entry is smaller or equal to 1.0. In practice, one often quantizes the descriptor entries to the range [0, 255] to reduce memory consumption (1 byte instead of 4 bytes for a floating point number). This has shown to have little impact on performance and is used here.

If you train your vocabulary on descriptors that are normalized to unit length, I would expect that the resulting vocabulary is not very useful for quantized descriptors (I'd expect that most descriptors are assigned to a few words, which would explain why the query time is so slow).

**Comment by francescoli** [comment]
@tsattler Just now, I tested the Vocabulary with the same images of database using hesaff. But the query time is still very slow. PerformSpatialVerification almost took 180 seconds and num_matches was 1030.

**Comment by tsattler** [comment]
@francescoli How many visual words are you using?

The spatial verification approach performs exhaustive hypothesis verification, where each match defines a pose hypothesis and each hypothesis is evaluated on all matches. As a result, the run-time is O(N^2) for N matches, which can be slow if N is large. If verification time is an issue, you can change the spatial verification to a RANSAC-like process or use a faster spatial verification algorithm (such as the one implemented in COLMAP).

**Comment by francescoli** [comment]
@tsattler  There are 70,000 words in the vocabulary. The faster spatial verification is Vote-and-Verify?

**Comment by tsattler** [comment]
@francescoli You could try to use a 100k or 200k vocabulary.

Yes, the faster verification is Vote-and-Verify.
