### ISSUE TITLE
About the query time

### ISSUE THREAD

**Issue by ownstyledu** [tsattler/geometric_burstiness#2]
@tsattler Hey tsattler, I just wonder how long should a query take? I collected 340 images as db and used a 20K vocabulary from Inria holidays and I modified the parameter num_words to 20K in the computing_hamming_thresholds.cc. 
As I set the nearest words num to 1 ( as asked in the README ) in every step, I simoutaneously modified the kNumNNWords to 1 in the query.cc. However , when I started in this condition, it has taken too long to run, the result file was updated every other several minutes. So, is there anything wrong about my settings?

**Comment by tsattler** [comment]
@ownstyledu How did you extract the features for your database images? Did you use a feature extractor that is compatible with the holidays vocabulary? Otherwise, what might happen is that all features are assigned to the same (or a few words), which should result in very slow run-times. Otherwise, the run-times should be in the order of seconds.

**Comment by francescoli** [comment]
@tsattler It seems that I meet this problem too. The images of the database are captured uniformly on the trajectory of the camera inside the room. So the adjacent ones look all the same. Does it matter? I trained the vocabulary with the dataset ANN_SIFT1M(http://corpus-texmex.irisa.fr/), and both database images and query images are extracted with hesaff. Anything Wrong?

Here is the log
```
 Loading the inverted index 
 Index loaded 
 Weights loaded 
 Found 2 query files 
 Found 836 db images in image_db.txt

 Query 0 : ./q/000230.jpg.bin

  Prepared 1287 query descriptors 
  Computing the self-similarity for the query image from 1287 query descriptors 
  Self-similarity: 26333.7
  Normalization weight 0.00616232
  Query found 836 potentially relevant database images
  Score of most relevant image 0.0912435 (image 726) with 4322 matches
  Starting spatial verification
```
