### ISSUE TITLE
How to train the codebook?

### ISSUE THREAD

**Issue by wangmaoCS** [tsattler/geometric_burstiness#3]
My respected Dr Sattler:

I'm trying to evaluate the code with the Pittsburgh dataset .
I have select 20k images from the dataset and extracted Hessian affine sift features (using the code from CUVT, Perdoch, sift_type=2) to train the 200k codebook, which have about 17M features.

Finally, I only achieve the recall@1 = 0.47, which is lower than the Disloc reported (about 0.55) 

Could you make the codebook public ?

**Comment by tsattler** [comment]
Did you convert the SIFT features to RootSIFT features before computing the codebook?
Notice that the features used by the program have descriptor entries scaled to the range [0, 255], so please make sure that the SIFT features are not normalized before you compute the codebook.

**Comment by wangmaoCS** [comment]
Does the advice of  not normalizing SIFT mean only using RootSIFT in the range [0,1] (only L1 normalization and square root from SIFT, no scaling) for codebook training?

**Comment by tsattler** [comment]
The advice is to use the RootSIFT descriptors computed via ``hesaff_sift_to_binary_root_sift`` and not perform any manipulation on them before training the codebook.

**Comment by wangmaoCS** [comment]
Yes, I used the result of `hesaff_sift_to_binary_root_sift` for codebook training. 
Thanks for your advice
