### ISSUE TITLE
The definition of place

### ISSUE THREAD

**Issue by wangmaoCS** [tsattler/geometric_burstiness#6]
For the function ReRankingInterPlaceGeometricBurstiness in the ranking_schemes.h, the purpose of lines of 255-234  makes me confused. 
When a new place is found, the other image will be update the place information based on the previous min distance and the new distance between the image and the place. 
However, the distance is still computed as the distance from the first image.

Is this right?

**Comment by tsattler** [comment]
@wangmaoCS  Sorry for the late reply. This issue somehow skipped my attention.

There indeed was a bug in the code. The update should have been based on the distance to the most recently selected cluster center. I just fixed the bug.

In the paper, we had originally implemented this part in matlab and I re-implemented it for the code release. I guess I introduced a copy-and-paste error here.
