### ISSUE TITLE
How to extract the local feature?

### ISSUE THREAD

**Issue by wangmaoCS** [tsattler/geometric_burstiness#9]
If I have detect_points.ln and compute_descriptors.ln for extracting local features, such as the software provided in http://www.robots.ox.ac.uk/~vgg/research/affine/detectors.html#binaries. How to extract the local feature?

Could you give use the demo shell script to extract local features of an image in your experiments?

I want to verify if I correctly extract the local feature.

Thanks in advance!

**Comment by tsattler** [comment]
Examples on how to run the two executables should be given here: http://www.robots.ox.ac.uk/~vgg/research/affine/
